name: retail_app
description: "Retail app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.6.0
  go_router: ^14.2.3
  dio: ^5.6.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  retrofit_generator: ^8.2.0
  provider: ^6.0.5
  convex_bottom_bar: ^3.2.0
  google_fonts: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  build_runner_core: ^7.3.2
  logging: ^1.2.0


flutter:
  uses-material-design: true
