name: retail_admin
description: "Retail admin app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  retail_core:
    path: ../retail_core
  cupertino_icons: ^1.0.8
  get_it: ^7.6.0
  go_router: ^14.2.3
  dio: ^5.6.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  retrofit_generator: ^8.2.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  build_runner_core: ^7.3.2
  logging: ^1.2.0

flutter_native_splash:
  color: "#0f1218"
  image: assets/core/splash_icon.png

flutter:
  uses-material-design: true
